version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - depguard
  settings:
    depguard:
      rules:
        core-integrations:
          list-mode: lax
          deny:
            - pkg: k8s.io/
              desc: "Use toolexec-integrations/kubernetes instead of client-go in core"
            - pkg: github.com/docker/
              desc: "Docker SDK is not allowed in toolexec core"
            - pkg: github.com/containerd/
              desc: "containerd SDK is not allowed in toolexec core"
            - pkg: github.com/firecracker-microvm/
              desc: "Firecracker SDK is not allowed in toolexec core"
            - pkg: github.com/tetratelabs/wazero
              desc: "WASM runtimes belong in integrations"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jonwraymond

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
